---
- hosts: all
  become: true
  vars:
      is_container: false

  roles:

      - role: "{{ playbook_dir }}"
        rhel8cis_system_is_container: "{{ is_container | default(false) }}"
        rhel8cis_skip_for_travis: false
        
        perform_live_checks: true
        live_checks_file: tasks/live_checks/repo_live_checks.yml
        live_checks_host: 127.0.0.1
