---
- name: wget from host and check response
  get_url:
    url: http://192.168.179.167/
    dest: /home/admin/index.html

- name: Check in index
  lineinfile: 
    path: /home/admin/index.html
    line: "Index of /centos/"
    state: present
  check_mode: yes
  register: presence
  failed_when: presence.changed