---
- name: wget from host and check response
  get_url:
    url: http://192.168.179.167/centos
    dest: /home/admin/index.html

- name: Read html
  shell: cat /home/admin/index.html
  register: html

- name: Check if file still working
  debug:
    msg: "File Compare"
  failed_when: html.stdout.find("<head><title>Index of /centos/</title></head>") != -1