---
- name: Perform live checks
  block:

    - name: wget from host and check response
      get_url:
        url: http://192.168.179.167/centos
        dest: /home/admin/index.html

    - name: Get output for test
      shell: cat /home/admin/index.html | grep 'Index of /centos'
      register: op

    - debug:
        msg: "Test that server is still running"
      failed_when: op.stdout_lines | length == 0

  delegate_to: "{{live_checks_host}}"