---
- name: Perform live checks
  block:

    - name: Perform Chronyd time check against host
      shell: "chronyd -Q ' server {{inventory_host}} iburst' | grep 'No suitable source for synchronisation'"
      register: op

    - debug:
        msg: "Test that ntp server is still running"
      failed_when: op.stdout_lines | length == 0

  delegate_to: "{{live_checks_host}}"
